//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Math.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MathParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface IMathListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.calc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCalc([NotNull] MathParser.CalcContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.calc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCalc([NotNull] MathParser.CalcContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MathParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] MathParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MathParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] MathParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Const</c>
	/// labeled alternative in <see cref="MathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConst([NotNull] MathParser.ConstContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Const</c>
	/// labeled alternative in <see cref="MathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConst([NotNull] MathParser.ConstContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Paren</c>
	/// labeled alternative in <see cref="MathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParen([NotNull] MathParser.ParenContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Paren</c>
	/// labeled alternative in <see cref="MathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParen([NotNull] MathParser.ParenContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Arithmetic</c>
	/// labeled alternative in <see cref="MathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmetic([NotNull] MathParser.ArithmeticContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Arithmetic</c>
	/// labeled alternative in <see cref="MathParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmetic([NotNull] MathParser.ArithmeticContext context);
}
